INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Afghan afghani', '؋', 'AFN', 'Pul');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Albanian lek', 'L', 'ALL', 'Qindarkë');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Guernsey pound', '£', 'GGP', 'Penny');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Angolan kwanza', 'Kz', 'AOA', 'Cêntimo');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Argentine peso', '$', 'ARS', 'Centavo');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Aruban florin', 'ƒ', 'AWG', 'Cent');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Euro', '€', 'EUR', 'Cent');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Azerbaijani manat', '', 'AZN', 'Qəpik');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Bahamian dollar', '$', 'BSD', 'Cent');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Bahraini dinar', '.د.ب', 'BHD', 'Fils');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Bangladeshi taka', '৳', 'BDT', 'Paisa');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Barbadian dollar', '$', 'BBD', 'Cent');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Belarusian ruble', 'Br', 'BYR', 'Kapyeyka');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Belize dollar', '$', 'BZD', 'Cent');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Bermudian dollar', '$', 'BMD', 'Cent');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Bhutanese ngultrum', 'Nu.', 'BTN', 'Chetrum');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Bolivian boliviano', 'Bs.', 'BOB', 'Centavo');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Bosnia and Herzegovina convertible mark', 'KM or КМ', 'BAM', 'Fening');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Brazilian real', 'R$', 'BRL', 'Centavo');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Bulgarian lev', 'лв', 'BGN', 'Stotinka');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Burundian franc', 'Fr', 'BIF', 'Centime');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Cambodian riel', '៛', 'KHR', 'Sen');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Canadian dollar', '$', 'CAD', 'Cent');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Cape Verdean escudo', 'Esc or $', 'CVE', 'Centavo');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Cayman Islands dollar', '$', 'KYD', 'Cent');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Chilean peso', '$', 'CLP', 'Centavo');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Chinese yuan', '¥ or 元', 'CNY', 'Fen');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Colombian peso', '$', 'COP', 'Centavo');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Comorian franc', 'Fr', 'KMF', 'Centime');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Congolese franc', 'Fr', 'CDF', 'Centime');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Costa Rican colón', '₡', 'CRC', 'Céntimo');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Croatian kuna', 'kn', 'HRK', 'Lipa');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Cuban convertible peso', '$', 'CUC', 'Centavo');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Cuban peso', '$', 'CUP', 'Centavo');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Czech koruna', 'Kč', 'CZK', 'Haléř');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Djiboutian franc', 'Fr', 'DJF', 'Centime');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Dominican peso', '$', 'DOP', 'Centavo');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Egyptian pound', '£ or ج.م', 'EGP', 'Piastre');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Eritrean nakfa', 'Nfk', 'ERN', 'Cent');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Ethiopian birr', 'Br', 'ETB', 'Santim');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Falkland Islands pound', '£', 'FKP', 'Penny');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Danish krone', 'kr', 'DKK', 'Øre');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Fijian dollar', '$', 'FJD', 'Cent');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Central African CFA franc', 'Fr', 'XAF', 'Centime');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Gambian dalasi', 'D', 'GMD', 'Butut');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Georgian lari', 'ლ', 'GEL', 'Tetri');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Ghana cedi', '₵', 'GHS', 'Pesewa');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Gibraltar pound', '£', 'GIP', 'Penny');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Guatemalan quetzal', 'Q', 'GTQ', 'Centavo');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Guinean franc', 'Fr', 'GNF', 'Centime');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Guyanese dollar', '$', 'GYD', 'Cent');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Haitian gourde', 'G', 'HTG', 'Centime');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Honduran lempira', 'L', 'HNL', 'Centavo');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Hong Kong dollar', '$', 'HKD', 'Cent');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Hungarian forint', 'Ft', 'HUF', 'Fillér');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Icelandic króna', 'kr', 'ISK', 'Eyrir');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Indian rupee', '₹', 'INR', 'Paisa');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Indonesian rupiah', 'Rp', 'IDR', 'Sen');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Iranian rial', '﷼', 'IRR', 'Dinar');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Iraqi dinar', 'ع.د', 'IQD', 'Fils');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Jamaican dollar', '$', 'JMD', 'Cent');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Japanese yen', '¥', 'JPY', 'Sen');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Kazakhstani tenge', '', 'KZT', 'Tïın');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Kenyan shilling', 'Sh', 'KES', 'Cent');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'North Korean won', '₩', 'KPW', 'Chon');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'South Korean won', '₩', 'KRW', 'Jeon');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Kuwaiti dinar', 'د.ك', 'KWD', 'Fils');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Kyrgyzstani som', 'лв', 'KGS', 'Tyiyn');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Lao kip', '₭', 'LAK', 'Att');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Lebanese pound', 'ل.ل', 'LBP', 'Piastre');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Lesotho loti', 'L', 'LSL', 'Sente');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Liberian dollar', '$', 'LRD', 'Cent');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Libyan dinar', 'ل.د', 'LYD', 'Dirham');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Macanese pataca', 'P', 'MOP', 'Avo');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Macedonian denar', 'ден', 'MKD', 'Deni');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Malagasy ariary', 'Ar', 'MGA', 'Iraimbilanja');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Malawian kwacha', 'MK', 'MWK', 'Tambala');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Malaysian ringgit', 'RM', 'MYR', 'Sen');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Maldivian rufiyaa', '.ރ', 'MVR', 'Laari');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Mauritian rupee', '₨', 'MUR', 'Cent');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Mexican peso', '$', 'MXN', 'Centavo');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Moldovan leu', 'L', 'MDL', 'Ban');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Mongolian tögrög', '₮', 'MNT', 'Möngö');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Mozambican metical', 'MT', 'MZN', 'Centavo');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Burmese kyat', 'Ks', 'MMK', 'Pya');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Armenian dram', '', 'AMD', 'Luma');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Namibian dollar', '$', 'NAD', 'Cent');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Nepalese rupee', '₨', 'NPR', 'Paisa');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Nicaraguan córdoba', 'C$', 'NIO', 'Centavo');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Nigerian naira', '₦', 'NGN', 'Kobo');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Norwegian krone', 'kr', 'NOK', 'Øre');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Omani rial', 'ر.ع.', 'OMR', 'Baisa');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Pakistani rupee', '₨', 'PKR', 'Paisa');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Israeli new shekel', '₪', 'ILS', 'Agora');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Jordanian dinar', 'د.ا', 'JOD', 'Piastre');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Panamanian balboa', 'B/.', 'PAB', 'Centésimo');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Papua New Guinean kina', 'K', 'PGK', 'Toea');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Paraguayan guaraní', '₲', 'PYG', 'Céntimo');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Peruvian nuevo sol', 'S/.', 'PEN', 'Céntimo');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Philippine peso', '₱', 'PHP', 'Centavo');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'New Zealand dollar', '$', 'NZD', 'Cent');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Polish złoty', 'zł', 'PLN', 'Grosz');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Qatari riyal', 'ر.ق', 'QAR', 'Dirham');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Romanian leu', 'lei', 'RON', 'Ban');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Rwandan franc', 'Fr', 'RWF', 'Centime');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Algerian dinar', 'د.ج', 'DZD', 'Santeem');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Mauritanian ouguiya', 'UM', 'MRO', 'Khoums');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Moroccan dirham', 'د. م.', 'MAD', 'Centime');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'East Caribbean dollar', '$', 'XCD', 'Cent');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Samoan tālā', 'T', 'WST', 'Sene');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'São Tomé and Príncipe dobra', 'Db', 'STD', 'Cêntimo');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Saudi riyal', 'ر.س', 'SAR', 'Halala');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Serbian dinar', 'дин. or din.', 'RSD', 'Para');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Seychellois rupee', '₨', 'SCR', 'Cent');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Sierra Leonean leone', 'Le', 'SLL', 'Cent');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Brunei dollar', '$', 'BND', 'Sen');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Singapore dollar', '$', 'SGD', 'Cent');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Netherlands Antillean guilder', 'ƒ', 'ANG', 'Cent');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Solomon Islands dollar', '$', 'SBD', 'Cent');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Somali shilling', 'Sh', 'SOS', 'Cent');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'South Sudanese pound', '£', 'SSP', 'Piastre');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Sri Lankan rupee', 'Rs or රු', 'LKR', 'Cent');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Sudanese pound', 'ج.س.', 'SDG', 'Piastre');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Surinamese dollar', '$', 'SRD', 'Cent');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Swazi lilangeni', 'L', 'SZL', 'Cent');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Swedish krona', 'kr', 'SEK', 'Öre');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Swiss franc', 'Fr', 'CHF', 'Rappen');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Syrian pound', '£ or ل.س', 'SYP', 'Piastre');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'New Taiwan dollar', '$', 'TWD', 'Cent');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Tajikistani somoni', 'ЅМ', 'TJS', 'Diram');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Tanzanian shilling', 'Sh', 'TZS', 'Cent');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Thai baht', '฿', 'THB', 'Satang');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'West African CFA franc', 'Fr', 'XOF', 'Centime');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Tongan paʻanga', 'T$', 'TOP', 'Seniti');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Trinidad and Tobago dollar', '$', 'TTD', 'Cent');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Saint Helena pound', '£', 'SHP', 'Penny');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Tunisian dinar', 'د.ت', 'TND', 'Millime');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Turkish lira', '', 'TRY', 'Kuruş');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Turkmenistan manat', 'm', 'TMT', 'Tennesi');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Australian dollar', '$', 'AUD', 'Cent');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Ugandan shilling', 'Sh', 'UGX', 'Cent');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Ukrainian hryvnia', '₴', 'UAH', 'Kopiyka');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Russian ruble', '', 'RUB', 'Kopek');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'United Arab Emirates dirham', 'د.إ', 'AED', 'Fils');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Uruguayan peso', '$', 'UYU', 'Centésimo');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Uzbekistani som', '', 'UZS', 'Tiyin');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Vanuatu vatu', 'Vt', 'VUV', '');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Venezuelan bolívar', 'Bs F', 'VEF', 'Céntimo');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Vietnamese đồng', '₫', 'VND', '');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'CFP franc', 'Fr', 'XPF', 'Centime');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Yemeni rial', '﷼', 'YER', 'Fils');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Zambian kwacha', 'ZK', 'ZMW', 'Ngwee');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'Botswana pula', 'P', 'BWP', 'Thebe');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'British pound', '£', 'GBP', 'Penny');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'South African rand', 'R', 'ZAR', 'Cent');
INSERT INTO "gen_currency" ("id", "c_name", "c_symbol", "c_shortname", "c_fractional_unit") VALUES (uuid_generate_v1(), 'United States dollar', '$', 'USD', 'Cent');
