INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '1', 'AF', 'Afghanistan', '93');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '2', 'AL', 'Albania', '355');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '3', 'DZ', 'Algeria', '213');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '4', 'AS', 'American Samoa', '1684');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '5', 'AD', 'Andorra', '376');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '6', 'AO', 'Angola', '244');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '7', 'AI', 'Anguilla', '1264');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '8', 'AQ', 'Antarctica', '');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '9', 'AG', 'Antigua And Barbuda', '1268');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '10', 'AR', 'Argentina', '54');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '11', 'AM', 'Armenia', '374');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '12', 'AW', 'Aruba', '297');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '13', 'AU', 'Australia', '61');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '14', 'AT', 'Austria', '43');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '15', 'AZ', 'Azerbaijan', '994');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '16', 'BS', 'Bahamas The', '1242');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '17', 'BH', 'Bahrain', '973');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '18', 'BD', 'Bangladesh', '880');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '19', 'BB', 'Barbados', '1246');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '20', 'BY', 'Belarus', '375');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '21', 'BE', 'Belgium', '32');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '22', 'BZ', 'Belize', '501');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '23', 'BJ', 'Benin', '229');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '24', 'BM', 'Bermuda', '1441');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '25', 'BT', 'Bhutan', '975');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '26', 'BO', 'Bolivia', '591');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '27', 'BA', 'Bosnia and Herzegovina', '387');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '28', 'BW', 'Botswana', '267');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '29', 'BV', 'Bouvet Island', '');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '30', 'BR', 'Brazil', '55');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '31', 'IO', 'British Indian Ocean Territory', '246');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '32', 'BN', 'Brunei', '673');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '33', 'BG', 'Bulgaria', '359');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '34', 'BF', 'Burkina Faso', '226');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '35', 'BI', 'Burundi', '257');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '36', 'KH', 'Cambodia', '855');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '37', 'CM', 'Cameroon', '237');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '38', 'CA', 'Canada', '1');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '39', 'CV', 'Cape Verde', '238');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '40', 'KY', 'Cayman Islands', '1345');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '41', 'CF', 'Central African Republic', '236');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '42', 'TD', 'Chad', '235');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '43', 'CL', 'Chile', '56');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '44', 'CN', 'China', '86');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '45', 'CX', 'Christmas Island', '61');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '46', 'CC', 'Cocos (Keeling) Islands', '672');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '47', 'CO', 'Colombia', '57');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '48', 'KM', 'Comoros', '269');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '49', 'CG', 'Republic Of The Congo', '242');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '50', 'CD', 'Democratic Republic Of The Congo', '242');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '51', 'CK', 'Cook Islands', '682');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '52', 'CR', 'Costa Rica', '506');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '53', 'CI', 'Cote DIvoire (Ivory Coast)', '225');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '54', 'HR', 'Croatia (Hrvatska)', '385');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '55', 'CU', 'Cuba', '53');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '56', 'CY', 'Cyprus', '357');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '57', 'CZ', 'Czech Republic', '420');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '58', 'DK', 'Denmark', '45');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '59', 'DJ', 'Djibouti', '253');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '60', 'DM', 'Dominica', '1767');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '61', 'DO', 'Dominican Republic', '1809');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '62', 'TP', 'East Timor', '670');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '63', 'EC', 'Ecuador', '593');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '64', 'EG', 'Egypt', '20');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '65', 'SV', 'El Salvador', '503');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '66', 'GQ', 'Equatorial Guinea', '240');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '67', 'ER', 'Eritrea', '291');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '68', 'EE', 'Estonia', '372');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '69', 'ET', 'Ethiopia', '251');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '70', 'XA', 'External Territories of Australia', '61');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '71', 'FK', 'Falkland Islands', '500');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '72', 'FO', 'Faroe Islands', '298');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '73', 'FJ', 'Fiji Islands', '679');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '74', 'FI', 'Finland', '358');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '75', 'FR', 'France', '33');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '76', 'GF', 'French Guiana', '594');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '77', 'PF', 'French Polynesia', '689');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '78', 'TF', 'French Southern Territories', '');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '79', 'GA', 'Gabon', '241');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '80', 'GM', 'Gambia The', '220');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '81', 'GE', 'Georgia', '995');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '82', 'DE', 'Germany', '49');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '83', 'GH', 'Ghana', '233');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '84', 'GI', 'Gibraltar', '350');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '85', 'GR', 'Greece', '30');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '86', 'GL', 'Greenland', '299');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '87', 'GD', 'Grenada', '1473');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '88', 'GP', 'Guadeloupe', '590');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '89', 'GU', 'Guam', '1671');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '90', 'GT', 'Guatemala', '502');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '91', 'XU', 'Guernsey and Alderney', '44');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '92', 'GN', 'Guinea', '224');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '93', 'GW', 'Guinea-Bissau', '245');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '94', 'GY', 'Guyana', '592');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '95', 'HT', 'Haiti', '509');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '96', 'HM', 'Heard and McDonald Islands', '');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '97', 'HN', 'Honduras', '504');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '98', 'HK', 'Hong Kong S.A.R.', '852');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '99', 'HU', 'Hungary', '36');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '100', 'IS', 'Iceland', '354');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '101', 'IN', 'India', '91');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '102', '"ID"', 'Indonesia', '62');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '103', 'IR', 'Iran', '98');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '104', 'IQ', 'Iraq', '964');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '105', 'IE', 'Ireland', '353');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '106', 'IL', 'Israel', '972');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '107', 'IT', 'Italy', '39');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '108', 'JM', 'Jamaica', '1876');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '109', 'JP', 'Japan', '81');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '110', 'XJ', 'Jersey', '44');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '111', 'JO', 'Jordan', '962');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '112', 'KZ', 'Kazakhstan', '7');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '113', 'KE', 'Kenya', '254');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '114', 'KI', 'Kiribati', '686');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '115', 'KP', 'Korea North', '850');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '116', 'KR', 'Korea South', '82');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '117', 'KW', 'Kuwait', '965');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '118', 'KG', 'Kyrgyzstan', '996');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '119', 'LA', 'Laos', '856');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '120', 'LV', 'Latvia', '371');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '121', 'LB', 'Lebanon', '961');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '122', 'LS', 'Lesotho', '266');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '123', 'LR', 'Liberia', '231');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '124', 'LY', 'Libya', '218');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '125', 'LI', 'Liechtenstein', '423');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '126', 'LT', 'Lithuania', '370');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '127', 'LU', 'Luxembourg', '352');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '128', 'MO', 'Macau S.A.R.', '853');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '129', 'MK', 'Macedonia', '389');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '130', 'MG', 'Madagascar', '261');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '131', 'MW', 'Malawi', '265');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '132', 'MY', 'Malaysia', '60');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '133', 'MV', 'Maldives', '960');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '134', 'ML', 'Mali', '223');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '135', 'MT', 'Malta', '356');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '136', 'XM', 'Man (Isle of)', '44');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '137', 'MH', 'Marshall Islands', '692');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '138', 'MQ', 'Martinique', '596');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '139', 'MR', 'Mauritania', '222');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '140', 'MU', 'Mauritius', '230');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '141', 'YT', 'Mayotte', '269');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '142', 'MX', 'Mexico', '52');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '143', 'FM', 'Micronesia', '691');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '144', 'MD', 'Moldova', '373');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '145', 'MC', 'Monaco', '377');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '146', 'MN', 'Mongolia', '976');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '147', 'MS', 'Montserrat', '1664');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '148', 'MA', 'Morocco', '212');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '149', 'MZ', 'Mozambique', '258');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '150', 'MM', 'Myanmar', '95');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '151', 'NA', 'Namibia', '264');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '152', 'NR', 'Nauru', '674');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '153', 'NP', 'Nepal', '977');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '154', 'AN', 'Netherlands Antilles', '599');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '155', 'NL', 'Netherlands The', '31');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '156', 'NC', 'New Caledonia', '687');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '157', 'NZ', 'New Zealand', '64');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '158', 'NI', 'Nicaragua', '505');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '159', 'NE', 'Niger', '227');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '160', 'NG', 'Nigeria', '234');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '161', 'NU', 'Niue', '683');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '162', 'NF', 'Norfolk Island', '672');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '163', 'MP', 'Northern Mariana Islands', '1670');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '164', 'NO', 'Norway', '47');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '165', 'OM', 'Oman', '968');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '166', 'PK', 'Pakistan', '92');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '167', 'PW', 'Palau', '680');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '168', 'PS', 'Palestinian Territory Occupied', '970');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '169', 'PA', 'Panama', '507');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '170', 'PG', 'Papua new Guinea', '675');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '171', 'PY', 'Paraguay', '595');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '172', 'PE', 'Peru', '51');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '173', 'PH', 'Philippines', '63');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '174', 'PN', 'Pitcairn Island', '');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '175', 'PL', 'Poland', '48');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '176', 'PT', 'Portugal', '351');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '177', 'PR', 'Puerto Rico', '1787');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '178', 'QA', 'Qatar', '974');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '179', 'RE', 'Reunion', '262');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '180', 'RO', 'Romania', '40');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '181', 'RU', 'Russia', '70');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '182', 'RW', 'Rwanda', '250');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '183', 'SH', 'Saint Helena', '290');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '184', 'KN', 'Saint Kitts And Nevis', '1869');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '185', 'LC', 'Saint Lucia', '1758');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '186', 'PM', 'Saint Pierre and Miquelon', '508');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '187', 'VC', 'Saint Vincent And The Grenadines', '1784');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '188', 'WS', 'Samoa', '684');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '189', 'SM', 'San Marino', '378');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '190', 'ST', 'Sao Tome and Principe', '239');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '191', 'SA', 'Saudi Arabia', '966');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '192', 'SN', 'Senegal', '221');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '193', 'RS', 'Serbia', '381');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '194', 'SC', 'Seychelles', '248');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '195', 'SL', 'Sierra Leone', '232');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '196', 'SG', 'Singapore', '65');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '197', 'SK', 'Slovakia', '421');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '198', 'SI', 'Slovenia', '386');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '199', 'XG', 'Smaller Territories of the UK', '44');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '200', 'SB', 'Solomon Islands', '677');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '201', 'SO', 'Somalia', '252');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '202', 'ZA', 'South Africa', '27');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '203', 'GS', 'South Georgia', '');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '204', 'SS', 'South Sudan', '211');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '205', 'ES', 'Spain', '34');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '206', 'LK', 'Sri Lanka', '94');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '207', 'SD', 'Sudan', '249');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '208', 'SR', 'Suriname', '597');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '209', 'SJ', 'Svalbard And Jan Mayen Islands', '47');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '210', 'SZ', 'Swaziland', '268');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '211', 'SE', 'Sweden', '46');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '212', 'CH', 'Switzerland', '41');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '213', 'SY', 'Syria', '963');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '214', 'TW', 'Taiwan', '886');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '215', 'TJ', 'Tajikistan', '992');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '216', 'TZ', 'Tanzania', '255');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '217', 'TH', 'Thailand', '66');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '218', 'TG', 'Togo', '228');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '219', 'TK', 'Tokelau', '690');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '220', 'TO', 'Tonga', '676');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '221', 'TT', 'Trinidad And Tobago', '1868');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '222', 'TN', 'Tunisia', '216');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '223', 'TR', 'Turkey', '90');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '224', 'TM', 'Turkmenistan', '7370');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '225', 'TC', 'Turks And Caicos Islands', '1649');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '226', 'TV', 'Tuvalu', '688');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '227', 'UG', 'Uganda', '256');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '228', 'UA', 'Ukraine', '380');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '229', 'AE', 'United Arab Emirates', '971');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '230', 'GB', 'United Kingdom', '44');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '231', 'US', 'United States', '1');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '232', 'UM', 'United States Minor Outlying Islands', '1');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '233', 'UY', 'Uruguay', '598');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '234', 'UZ', 'Uzbekistan', '998');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '235', 'VU', 'Vanuatu', '678');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '236', 'VA', 'Vatican City State (Holy See)', '39');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '237', 'VE', 'Venezuela', '58');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '238', 'VN', 'Vietnam', '84');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '239', 'VG', 'Virgin Islands (British)', '1284');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '240', 'VI', 'Virgin Islands (US)', '1340');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '241', 'WF', 'Wallis And Futuna Islands', '681');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '242', 'EH', 'Western Sahara', '212');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '243', 'YE', 'Yemen', '967');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '244', 'YU', 'Yugoslavia', '38');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '245', 'ZM', 'Zambia', '260');
INSERT INTO "gen_country" ("id", "oid", "sortname", "name", "phoneCode") VALUES (uuid_generate_v1(), '246', 'ZW', 'Zimbabwe', '26');
